dist: xenial
language: python
python:
  - "3.6"
  - "3.7"
  - "pypy3"
os:
  - linux
#  - osx  # osx+python installation fails
before_script:
  - python -m pip install pip --upgrade
  - python -m pip --version
  - export PYTHONHASHSEED=${PYTHONHASHSEED:-${RANDOM}}
  - echo "export PYTHONHASHSEED=${PYTHONHASHSEED}"
  - python -m pip install .[test]
  - python -m pip install codecov
  - export COVERAGE_PROCESS_START=$(pwd)/.coveragerc
  - export PYTEST_ADDOPTS=-v
script:
  - python -m flake8
  - |
    if [[ $TRAVIS_PYTHON_VERSION != 'pypy3'* ]]; then
      python -m black  --target-version py36 --check lapis/ lapis_tests/
    fi
  - python -m coverage run -m pytest
after_success:
  - coverage report && codecov
